### ISSUE TITLE
Is there an ANSI version of this awesome program?

### ISSUE THREAD

**Issue by Emasoft** [pwaller/pyfiglet#112]
Is there an ANSI version of this awesome program?

**Comment by pwaller** [comment]
I'm having some difficulty guessing what you're asking for. Do you mean the source code of the program should be [Windows-1252](http://en.wikipedia.org/wiki/Windows-1252), or the output of the program, or something else? Please can you clarify?

Please can you explain what functionality you're after in particular?

I'm going to pre-emptively close this, since I suspect it is off topic (what issue needs fixing?), but if you reply I'll reopen it.
