### ISSUE TITLE
Missing `requires_python`

### ISSUE THREAD

**Issue by paul105** [pwaller/pyfiglet#128]
Since you are missing `requires_python` in pyproject.toml, package is built for any Python version. This leads to the situation in which pyfiglet==1.0.0 is trying to be installed with Python 2.7 or Python 3.6, but it's not compatible anymore.

**Comment by pwaller** [comment]
pyfiglet currently uses setup.py still, so I take it we need to specify requires_python there.

Pull request is at #130. Please let me know if you spot whether this will not work.

**Comment by pwaller** [comment]
I added requires_python to the `setup()` invocation and ran CI through 3.8, but the installation does not complain. I trust that it will be sufficient that `pip` and friends won't choose this version.

Version 1.0.1 is now on pypi and I have yanked 1.0.0 to prevent old versions of python from selecting it. I understand that the rc should not be selected unless a user specifies an rc or `--pre` to `pip`. Can you please test if your problem is fixed and report back?

**Comment by pwaller** [comment]
Fixed in #130.
