### ISSUE TITLE
How to create your own figlet font?

### ISSUE THREAD

**Issue by Vortetty** [pwaller/pyfiglet#71]
how can i make my own font, i have looked at the files but it is confusing what order the symbols are in at the start, does anybody know what order i need to make the letters in, and the format? if you do, could you please share it.

alternatively, is there a font that looks like a casino machine font (i am making a slot machine: https://repl.it/@Vortetty/lucky-py-slots)

**Comment by pwaller** [comment]
A quick search lead me to http://patorjk.com/figlet-editor/#/edit

I don't have any advice on the topic myself. Please feel free to add more links to resources on this issue.

(Advice if you ever submit future issues to this repository or any other: please try to make the title of the subject meaningful, otherwise it's harder to know what the issue is about when looking at a list of issues).

**Comment by BlanXyz** [comment]
Found this:
http://www.jave.de/figlet/figfont.html#creating
