### ISSUE TITLE
Font Licensing

### ISSUE THREAD

**Issue by LyesSaadi** [pwaller/pyfiglet#89]
Hello :),

A while ago (nearly a year!), [I submitted pyfiglet for inclusion in the Fedora repositories](https://bugzilla.redhat.com/show_bug.cgi?id=1876108). It was approved, but its inclusion was aborted as I found out about all the fonts included and nearly fainted at the sight of reviewing each of these fonts licenses. In retrospect, I should've contacted you to help me with those issues, which is why I decided to do it now.

Indeed, today @peterbrittain found out by luck of our effort to package pyfiglet and let us know that all the fonts which were not distributable were removed (as per #59). That is great, but unfortunately not enough. Indeed, for Fedora, it is required that the license of each font is documented and shipped with its license. And this package has fonts... A lot of them... And most are undocumented.

I also found out thanks to @peterbrittain that [there is prior art in FIGlet licensing](https://bugzilla.redhat.com/show_bug.cgi?id=820642) in Fedora, and what I seem to take out from that discussion is that if the shape and appearance of the fonts themselves are Public Domain, the files still remain under a font license.

So, what needs to be done is the curation of each font file in this repository. What could also be done is the creation of a new repository containing non-free or lost fonts that users can add easily using `pyfiglet -L`, while keeping safe fonts in the main repository.

**Comment by peterbrittain** [comment]
Looks like there are still fonts that won't make the cut for Fedora...  Maybe we can provide two different builds of pyfiglet?  One that only includes truly safe fonts (based on figlet precedent or clear license in the file) and one that also includes contributions (of legally grey fonts).  Fedora could build one and you could continue to build and distribute the other.

Code-wise it could be two separate directories and a simple environmental flag (or something similar) to determine the build.  Or do you need completely clean source repos @LyesSaadi ?

**Comment by LyesSaadi** [comment]
> Code-wise it could be two separate directories and a simple environmental flag (or something similar) to determine the build. Or do you need completely clean source repos @LyesSaadi ?

I have no issue with having them in two separate directories (maybe a `contrib` subdirectory in fonts ?).

**Comment by peterbrittain** [comment]
I had a quick play today...  I think the simplest change is to create 2 new directories (say, standard and contrib) and then move all the fonts into one of those.  Anything that can be shown to come from standard figlet fonts or has a suitably clear license goes into standard, while the rest go into contrib.  We can then update the Makefile to build 2 different packages (one for Fedora, the other for pypi).

Does that work for you @pwaller ?

**Comment by pwaller** [comment]
Hi! I'm very happy to accept changes which improve the situation under your guidance. Will be quite happy if one of you is able to make a PR, the other accept it in review, then I will review it and likely merge it quite quickly. Ideally it doesn't break anyone's existing workflow too badly, so if possible (if we don't already) can we provide a message instructing the user about the situation and what they can do to rectify it?

Apologies but I don't have tons of time to fault all of the state into my internal memory. Also if any of you folks know someone who would like to take on collective maintainer-ship I'd be happy to move this into an org and share ownership. Given that this project has take on more of a life of its own than I ever imagined it would, I don't like the fact it has a bus number of one right now, and really this belongs to the community, I merely gate-keep at the moment and my cycles are limited.

All the best, and thanks gain for looking into this.

**Comment by peterbrittain** [comment]
Ok!  I'm happy to make the proposed change (and some extra docs)...  The key questions are therefore:

- @LyesSaadi - what is an acceptable license inside the font files?
- @pwaller - what do you want to do about fonts that don't hit that bar?

I'm assuming that we need something clearly stating font distribution is allowed (for the former) and that pypi already has these fonts, so we continue to put them in the full package (for the latter), but update the docs to say we are willing to remove any if the owners get in touch.

Is that right?

**Comment by pwaller** [comment]
SGTM.

**Comment by LyesSaadi** [comment]
Basically, all fonts in the «Good» lists in [this wiki page](https://fedoraproject.org/wiki/Licensing:Main) are fine. If a license is missing in those lists, it needs to be approved by Fedora's Legal Team beforehand. Any font that does not make the cut, but is still redistributable, could eventually be packaged in a separate package in RPM Fusion (a semi-official repository for proprietary and legally problematic packages).

Also, a Makefile is not necessary, I could just remove the fonts in the RPM package myself. Still, isolating them in a `contrib` subdirectory would make my job, and that of every packager, easier as well as help users know under which type of License is everything. What Fedora considers as a Good License is also what is considered as a Good License by most of the other distributions like Debian, Ubuntu or OpenSUSE.

What would be great as well is having a file in the root of the directory explaining under which License is each font, and also having a subdirectory with all the Licenses in it, as most Licenses require to ship a copy of it with each copy of the Licensed material.

**Comment by peterbrittain** [comment]
Ok...  Most font files have no formal license, so I think we'll be down to just the original list from figlet at this point.  I'll check if any have a more legal framing in the next few days...  A quick scan showed a few that might contain an MIT licence.  Will let you know what I find.

**Comment by peterbrittain** [comment]
Sorry for the radio silence...  Took a while to find a free slot to look at all the files!  :-)

At a high level, there are various different cases:

- Many have no license at all
- Many also look like they were auomaticially converted from oter sources (e.g. search for PETSCII) 
- There are several .TLF (toilet fonts?) that have a license but aren't distributed (as they don't match the setup.py filters)
- There are a few that offer modification, but no distro rights - (e.g. "Permission is hereby given to modify this font, as long as the modifier's name is placed on a comment line.").
- Then there are some that refer to some level of licensing.
- Separately, there are the original figlet fonts that were signed off for the figlet package in v2.2.4 (so I assume are this list: https://github.com/cmatsuoka/figlet/tree/2.2.4/fonts).

I think the only ones that are potentially valid for Fedora are going to be the last two bullets.  I'll send a separate messages about what's in each list and the type of license.  The rest I will put into the "contrib" directory that will only build for pypi.

**Comment by peterbrittain** [comment]
### Redistributed from figlet

banner.flf
big.flf
block.flf
bubble.flf
digital.flf
ivrit.flf
lean.flf
mini.flf
mnemonic.flf
script.flf
shadow.flf
slant.flf
small.flf
smscript.flf
smshadow.flf
smslant.flf
standard.flf
term.flf

**Comment by peterbrittain** [comment]
### Modified MIT
Files affected are:
5x7 (extra sentence at the end of standard MIT license)
5x8 (re-written warranties to name company)
6x9 (extra sentence at the end of standard MIT license)
License is broadly as follows:
COMMENT Permission is hereby granted, free of charge, to any person obtaining a copy
COMMENT of this software and associated documentation files (the "Software"), to deal
COMMENT in the Software without restriction, including without limitation the rights
COMMENT to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
COMMENT copies of the Software, and to permit persons to whom the Software is
COMMENT furnished to do so, subject to the following conditions:
COMMENT 
COMMENT The above copyright notice and this permission notice shall be included in
COMMENT all copies or substantial portions of the Software.
COMMENT 
COMMENT THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
COMMENT IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
COMMENT FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
COMMENT X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
COMMENT AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
COMMENT CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
COMMENT 
COMMENT Except as contained in this notice, the name of the X Consortium shall not be
COMMENT used in advertising or otherwise to promote the sale, use or other dealings
COMMENT in this Software without prior written authorization from the X Consortium.

**Comment by peterbrittain** [comment]
### Unknown permissive, free

Files affected are:

clb6x10.flf
clb8x10.flf
clb8x8.flf
cli8x8.flf
clr4x6.flf
clr5x10.flf
clr5x6.flf
clr5x8.flf
clr6x10.flf
clr6x6.flf
clr6x8.flf
clr7x10.flf
clr7x8.flf
clr8x10.flf
clr8x8.flf

License is:

COMMENT  Copyright 1989 Dale Schumacher, dal@syntel.mn.org
COMMENT                 399 Beacon Ave.
COMMENT                 St. Paul, MN  55104-3527
COMMENT  
COMMENT  Permission to use, copy, modify, and distribute this software and
COMMENT  its documentation for any purpose and without fee is hereby
COMMENT  granted, provided that the above copyright notice appear in all
COMMENT  copies and that both that copyright notice and this permission
COMMENT  notice appear in supporting documentation, and that the name of
COMMENT  Dale Schumacher not be used in advertising or publicity pertaining to
COMMENT  distribution of the software without specific, written prior
COMMENT  permission.  Dale Schumacher makes no representations about the
COMMENT  suitability of this software for any purpose.  It is provided "as
COMMENT  is" without express or implied warranty.

**Comment by peterbrittain** [comment]
### Adobe permissive, free

Files affected are:

courb.flf
courbi.flf
cour.flf
couri.flf
helvb.flf
helvbi.flf
helv.flf
helvi.flf
sbookb.flf
sbookbi.flf
sbook.flf
sbooki.flf
times.flf
xcourb.flf
xcourbi.flf
xcour.flf
xcouri.flf
xhelvb.flf
xhelvbi.flf
xhelv.flf
xhelvi.flf
xsbookb.flf
xsbookbi.flf
xsbook.flf
xsbooki.flf
xtimes.flf

License is:

COMMENT  Copyright 1984-1989, 1994 Adobe Systems Incorporated.
COMMENT  Copyright 1988, 1994 Digital Equipment Corporation.
COMMENT
COMMENT  Adobe is a trademark of Adobe Systems Incorporated which may be
COMMENT  registered in certain jurisdictions.
COMMENT  Permission to use these trademarks is hereby granted only in
COMMENT  association with the images described in this file.
COMMENT
COMMENT  Permission to use, copy, modify, distribute and sell this software
COMMENT  and its documentation for any purpose and without fee is hereby
COMMENT  granted, provided that the above copyright notices appear in all
COMMENT  copies and that both those copyright notices and this permission
COMMENT  notice appear in supporting documentation, and that the names of
COMMENT  Adobe Systems and Digital Equipment Corporation not be used in
COMMENT  advertising or publicity pertaining to distribution of the software
COMMENT  without specific, written prior permission.  Adobe Systems and
COMMENT  Digital Equipment Corporation make no representations about the
COMMENT  suitability of this software for any purpose.  It is provided "as
COMMENT  is" without express or implied warranty.
COMMENT -

**Comment by peterbrittain** [comment]
### Converted from xconsortium BDF files

Files affected are:

6x10.flf
briteb.flf
britebi.flf
brite.flf
britei.flf
sansb.flf
sansbi.flf
sans.flf
sansi.flf
ttyb.flf
tty.flf
xbrite.flf
xbritei.flf
xsansb.flf
xsansbi.flf
xsans.flf
xsansi.flf
xttyb.flf
xtty.flf

There is no license as such, but they are all conversions from BDF files that were clearly maintained by the Xconsortium in years gone by.  I did a quick google, but couldn't find anything obvious that instantly meant we should just take these.

**Comment by peterbrittain** [comment]
Net of all the above... I propose to make figlet, MIT, Dale Schumake and Adobe fonts standard and then all the rest goes into the contrib folder.  Are all those OK with you @LyesSaadi ?

As mentioned before, planned structure is to create 2 folders and update the Makefile to allow you to build python packages with either the "safe" or all fonts embedded in the package.  README will be updated to explain this.

**Comment by LyesSaadi** [comment]
> MIT, Dale Schumake and Adobe fonts standard
All those are MIT derivatives and functionally equivalent to it, so 100% fine.

The BDF files are fine if they were under a free license and are identical from there. I am still browsing the repositories to maybe find one of them.

**Comment by LyesSaadi** [comment]
> The BDF files are fine if they were under a free license and are identical from there. I am still browsing the repositories to maybe find one of them.

Wait, remembered something. In the US (Fedora's jurisdiction), typefaces are not copyright-able, only the code is. Who converted them? Apparently, a certain John Cowan, who seems to be active on GitHub as @johnwcowan, so he could give us his agreement. And he seems to put in the font « Public Domain » as copyright, that would probably be fine for Fedora. But maybe not for non-US project (like Ubuntu) if you wish to add it later on other distros. In that case, re-licensing would probably be fine?

**Comment by johnwcowan** [comment]
Here's the scoop as I understand it.  (Note: I am not a lawyer, this is not legal advice.  But this is not the unauthorized practice of law, either.)

The first thing to understand is the difference between glyph shapes and fonts.  In the U.S., glyph shapes are *absolutely not* protected by copyright.  It does not matter if the shape is represented by a small metal object used in a letter press, a drawing of the shape, a list of pixels, or anything else, as these can all be mechanically converted from one to another, and no new copyrightable object is created (just as compiling C to an object file does not).

In particular, a BDF font (and therefore the FIGfonts derived from them) is just a sequence of glyph shapes, sizes, corresponding Unicode characters, etc.  It's data, and has no element of creativity except the glyph shapes, which as I say are not subject to U.S. copyright.

Now fonts as we usually understand them (TTF, OTF etc.) normally do not contain actual glyph images.  Rather, the contain curves that are combined to form the glyph image, plus "hints", which are written in  a special-purpse bytecode which allows a font engine to construct the exact glyph images desired.  This bytecode is legally considered software, and thus is subject to the usual obnoxious life+70 (or 90 for a corporation) copyright term.  (It's possible to embed a bitmap font into an OTF container; I don't know what the legal implications of that are.)

There is such a thing as a design patent which protects the visual qualities of a manufactured item.  If you make shoes of a specific shape, you can get a design patent on that shape, and so i opbut people hardly ever do.  They are hard to get, as they require the patentee to establish originality (only about 150 have ever been issued altogether) and expire after 14 years.

In the UK and the EU, glyph images *are* subject to copyright, but the longest possible term is 25 years even if the images were registered.  The X fonts have been published at least since X11R1, which was released in 1987.   So as they had to be created before that, any such font copyrights would have expired by now.  (I doubt any of them were registered.)

Lastly, if you convert a TTF/OTF font to a BDF font, then provided you are licensed to use the TTF/OTF font, you are free to do so.  It is the equivalent, legally, of printing out the characters in the TTF font on paper at a large size, scanning them, and translating the scanned pixels to a BDF font.  I didn't in fact do this, but someone else could.

**Comment by peterbrittain** [comment]
Does this give you everything you need in that PR for your builds @LyesSaadi ?

**Comment by pwaller** [comment]
Merged. Where do we stand now, is this issue fully resolved, and would it be useful to cut a release now or soon. Are either of you aware of anything else it would be useful to get in before a release?

**Comment by peterbrittain** [comment]
My guess is that we should wait until we hear back from Fedora Legal...  Then create a release that corresponds to their judgement.

**Comment by johnwcowan** [comment]
I don't get why this wasn't already resolved.  The older thread (don't have
a link available) said that Legal was already consulted about FIGlet fonts.

**Comment by LyesSaadi** [comment]
Are you referring to this thread: https://bugzilla.redhat.com/show_bug.cgi?id=820642 ?

**Comment by LyesSaadi** [comment]
Just to resume what happened in this thread, I couldn't find any official conclusion from Fedora Legal, only some legal debate about what would be subject to copyright or not.

And the FE-Legal blocker ended up being lifted because all proprietary files were removed in a new release figlet anyway as a result of this discussion.

**Comment by johnwcowan** [comment]
Can you tell me which fonts were considered to be proprietary?  (as you
know, I don't think there are any proprietary figfonts, at least in the
U.S.)

Also, the "only on MS-DOS" font means that the *output* of figlet when
using this font, as well as the font file itself, is encoded not in ASCII
but in IBM code page 437, the original 8-bit encoding used by systems
running the U.S. version of MS-DOS.  Details of this encoding are available
at <https://en.wikipedia.org/wiki/Code_page_437>.  It is perfectly correct
to use this font in any current OS and pipe the output into iconv to
convert it to a more modern encoding such as UTF-8.

**Comment by pwaller** [comment]
Ping @LyesSaadi. Interested to know if anyone watching has any more input before we cut a new release. I'll ping again after a few more weeks.

**Comment by LyesSaadi** [comment]
Woops, sorry ! Have had a lot of things going on and I kind of forgot about this :sweat_smile: ! Will look into it later this week (don't hesitate to ping me more often...) !

**Comment by peterbrittain** [comment]
Any news?

**Comment by pwaller** [comment]
#92 is a new PR which adds lots of fonts, importing them from [figlet.js](https://github.com/patorjk/figlet.js). Anyone have any opinion(s) on how to evaluate those for inclusion?

* The PR author has pointed out that this other project is MIT licensed but my current understanding is that this is irrelevant when it comes to the font licensing.
* After a quick search I couldn't determine if effort had been applied to the font licensing situation in that other project, but it could be an existing art in this domain? I'm unsure.

**Comment by peterbrittain** [comment]
Yeah  - the fonts have their own copyright and license.

- If that is clearly covered in the font header with a compatible license, you can put it in fonts-standard.
- If they declare a commercial/proprietary license, we have to remove them.
- Otherwise they fall into the same bucket as many other figlet fonts and so can go into fonts-contrib.

I wouldn't be surprised if they all fall into the last group, but someone needs to check.

**Comment by LyesSaadi** [comment]
> Any news?

Woops, sorry for the late answer.

Anyway, waiting for the holidays to end before asking again !

**Comment by LyesSaadi** [comment]
> > Any news?
> 
> Woops, sorry for the late answer.
> 
> Anyway, waiting for the holidays to end before asking again !

Just asked for an update!

**Comment by pwaller** [comment]
Ping again. :)

**Comment by johnwcowan** [comment]
If you are pinging me personally, please tell me what you want me to do
exactly.  Thanks.

**Comment by LyesSaadi** [comment]
Well, there was some discussion with someone from Red Hat recently, now waiting :< !

The discussion : https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/LBXHUVBV3HXCRJKI2E2HG5CRFM72QBEP/

**Comment by johnwcowan** [comment]
Okay.  Let me mention that that the BDF fonts (in the contrib/bdffont
directory) are trivial derivatives of the X BDF-format fonts and so are
covered by the X license, so there should be no question about them.

**Comment by peterbrittain** [comment]
Feels like the wider licensing is hitting a brick wall.  Shall we just accept the standard fonts at this stage @LyesSaadi ?

**Comment by LyesSaadi** [comment]
Sorry, I have no update from Fedora Legal, I'll try to ping them once again, and make the package with the free fonts go forward. I wasn't able to answer earlier due to personal issues and a lack of free time, but, since I'm now on holidays, I'll be able to give more time to this :) !

**Comment by peterbrittain** [comment]
Agreed.  LMK if there's anything I can do to help...

**Comment by richardfontana** [comment]
Hi @LyesSaadi I thought I'd try to reach you here rather than on the Fedora legal list. I have lost track of what you are interested in packaging in Fedora. Is it just the contents of fonts-standard and excluding anything in fonts-contrib?

**Comment by LyesSaadi** [comment]
Hello :D !

For now, only fonts-standard. It'd be hard to convince Fedora Legal to sign off on fonts-contrib. I mean, it could be proposed for rpmfusion I guess as an addon ?

Also, sorry for dragging my feet, got covid and then kinda forgot about it ^^'... Will go to annoy the fedora legal list right now.

**Comment by LyesSaadi** [comment]
Oh, just saw you were from RedHat, are you interested in co-maintaining @richardfontana ?

**Comment by LyesSaadi** [comment]
Well, I guess I didn't need to send that e-mail :P! I didn't understand that you were from Legal! Anyway, thank you so much for taking care of this, with this, font licensing issues are closed, and the Fedora package will move forward :tada:!

**Comment by pwaller** [comment]
Great to see this thread resolved. Is there anything else you need from this side @LyesSaadi? I'm happy to include packaging information in this repository if it makes sense to do so. Please let us know which fedora releases/repositories it is or will be available in :)

**Comment by LyesSaadi** [comment]
Nope ! It's still waiting in the review process for now. I may speed this up by asking other packagers for a review swap soon-ish.

**Comment by peterbrittain** [comment]
IIUC, it just got unassigned, so a new reviewer is needed.

**Comment by LyesSaadi** [comment]
Yup, that's me, because the old reviewer wasn't assigning. It just now is showing in the queue for new reviewers to pick up, that's why I'm waiting for a bit before speeding this up.

**Comment by peterbrittain** [comment]
@LyesSaadi - I see that the legal block was removed, but I can't see anything moving on the original thread to add pyfiglet to Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1876108) which is now about to be closed due to lack of action.  Are you still interested in packaging up the project?  If so, is there anything I can do to help?

**Comment by LyesSaadi** [comment]
Hi ! Yes, I'm still interested, but I kinda forgot the review myself :sweat_smile: ! Will ask on devel for a review swap to pass this quickly.
